version: '2'
services:
  db:
    build: ./db
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cake
      - MYSQL_USER=cake
      - MYSQL_PASSWORD=cake
  web:
    build: ./web
    ports:
      - 80:80
    volumes:
      - ./project:/var/www/html
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    ports:
      - 8080:80
    links:
      - db