version: '2'
services:
  mysql:
    build: ./db
    container_name: mysql
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cake
      - MYSQL_USER=cake
      - MYSQL_PASSWORD=cake
  web:
    build: ./web
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./web/project:/var/www/html
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
    links:
      - mysql
    volumes:
      - /sessions