version: '2'
services:
  dbmysql:
    build: ./db
    container_name: dbmysql
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cake
      - MYSQL_USER=cake
      - MYSQL_PASSWORD=cake
  web:
    build: ./web
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./web/project:/var/www/html
    depends_on:
      - dbmysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    ports:
      - 8080:80
    links:
      - dbmysql